package com.book.address.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AddressBook service. Represents a row in the &quot;addressbook_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.book.address.model.impl.AddressBookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.book.address.model.impl.AddressBookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddressBook
 * @see com.book.address.model.impl.AddressBookImpl
 * @see com.book.address.model.impl.AddressBookModelImpl
 * @generated
 */
public interface AddressBookModel extends BaseModel<AddressBook>,
    StagedGroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a address book model instance should use the {@link AddressBook} interface instead.
     */

    /**
     * Returns the primary key of this address book.
     *
     * @return the primary key of this address book
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this address book.
     *
     * @param primaryKey the primary key of this address book
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this address book.
     *
     * @return the uuid of this address book
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this address book.
     *
     * @param uuid the uuid of this address book
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the address book ID of this address book.
     *
     * @return the address book ID of this address book
     */
    public long getAddressBookId();

    /**
     * Sets the address book ID of this address book.
     *
     * @param addressBookId the address book ID of this address book
     */
    public void setAddressBookId(long addressBookId);

    /**
     * Returns the group ID of this address book.
     *
     * @return the group ID of this address book
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this address book.
     *
     * @param groupId the group ID of this address book
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this address book.
     *
     * @return the company ID of this address book
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this address book.
     *
     * @param companyId the company ID of this address book
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this address book.
     *
     * @return the user ID of this address book
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this address book.
     *
     * @param userId the user ID of this address book
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this address book.
     *
     * @return the user uuid of this address book
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this address book.
     *
     * @param userUuid the user uuid of this address book
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this address book.
     *
     * @return the user name of this address book
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this address book.
     *
     * @param userName the user name of this address book
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this address book.
     *
     * @return the create date of this address book
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this address book.
     *
     * @param createDate the create date of this address book
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this address book.
     *
     * @return the modified date of this address book
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this address book.
     *
     * @param modifiedDate the modified date of this address book
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this address book.
     *
     * @return the name of this address book
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this address book.
     *
     * @param name the name of this address book
     */
    public void setName(String name);

    /**
     * Returns the email of this address book.
     *
     * @return the email of this address book
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this address book.
     *
     * @param email the email of this address book
     */
    public void setEmail(String email);

    /**
     * Returns the age of this address book.
     *
     * @return the age of this address book
     */
    public int getAge();

    /**
     * Sets the age of this address book.
     *
     * @param age the age of this address book
     */
    public void setAge(int age);

    /**
     * Returns the message of this address book.
     *
     * @return the message of this address book
     */
    @AutoEscape
    public String getMessage();

    /**
     * Sets the message of this address book.
     *
     * @param message the message of this address book
     */
    public void setMessage(String message);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.book.address.model.AddressBook addressBook);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.book.address.model.AddressBook> toCacheModel();

    @Override
    public com.book.address.model.AddressBook toEscapedModel();

    @Override
    public com.book.address.model.AddressBook toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
