package com.book.address.model.impl;

import com.book.address.model.AddressBook;
import com.book.address.model.AddressBookModel;
import com.book.address.model.AddressBookSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AddressBook service. Represents a row in the &quot;addressbook_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.book.address.model.AddressBookModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AddressBookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AddressBookImpl
 * @see com.book.address.model.AddressBook
 * @see com.book.address.model.AddressBookModel
 * @generated
 */
@JSON(strict = true)
public class AddressBookModelImpl extends BaseModelImpl<AddressBook>
    implements AddressBookModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a address book model instance should use the {@link com.book.address.model.AddressBook} interface instead.
     */
    public static final String TABLE_NAME = "addressbook_data";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "addressBookId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "email", Types.VARCHAR },
            { "age", Types.INTEGER },
            { "message", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table addressbook_data (uuid_ VARCHAR(75) null,addressBookId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,email VARCHAR(75) null,age INTEGER,message VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table addressbook_data";
    public static final String ORDER_BY_JPQL = " ORDER BY addressBook.addressBookId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY addressbook_data.addressBookId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.book.address.model.AddressBook"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.book.address.model.AddressBook"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.book.address.model.AddressBook"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UUID_COLUMN_BITMASK = 4L;
    public static long ADDRESSBOOKID_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.book.address.model.AddressBook"));
    private static ClassLoader _classLoader = AddressBook.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            AddressBook.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _addressBookId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _email;
    private int _age;
    private String _message;
    private long _columnBitmask;
    private AddressBook _escapedModel;

    public AddressBookModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static AddressBook toModel(AddressBookSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        AddressBook model = new AddressBookImpl();

        model.setUuid(soapModel.getUuid());
        model.setAddressBookId(soapModel.getAddressBookId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setEmail(soapModel.getEmail());
        model.setAge(soapModel.getAge());
        model.setMessage(soapModel.getMessage());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<AddressBook> toModels(AddressBookSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<AddressBook> models = new ArrayList<AddressBook>(soapModels.length);

        for (AddressBookSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _addressBookId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setAddressBookId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _addressBookId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return AddressBook.class;
    }

    @Override
    public String getModelClassName() {
        return AddressBook.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("addressBookId", getAddressBookId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("email", getEmail());
        attributes.put("age", getAge());
        attributes.put("message", getMessage());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long addressBookId = (Long) attributes.get("addressBookId");

        if (addressBookId != null) {
            setAddressBookId(addressBookId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String email = (String) attributes.get("email");

        if (email != null) {
            setEmail(email);
        }

        Integer age = (Integer) attributes.get("age");

        if (age != null) {
            setAge(age);
        }

        String message = (String) attributes.get("message");

        if (message != null) {
            setMessage(message);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getAddressBookId() {
        return _addressBookId;
    }

    @Override
    public void setAddressBookId(long addressBookId) {
        _columnBitmask = -1L;

        _addressBookId = addressBookId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getEmail() {
        if (_email == null) {
            return StringPool.BLANK;
        } else {
            return _email;
        }
    }

    @Override
    public void setEmail(String email) {
        _email = email;
    }

    @JSON
    @Override
    public int getAge() {
        return _age;
    }

    @Override
    public void setAge(int age) {
        _age = age;
    }

    @JSON
    @Override
    public String getMessage() {
        if (_message == null) {
            return StringPool.BLANK;
        } else {
            return _message;
        }
    }

    @Override
    public void setMessage(String message) {
        _message = message;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                AddressBook.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            AddressBook.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public AddressBook toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (AddressBook) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        AddressBookImpl addressBookImpl = new AddressBookImpl();

        addressBookImpl.setUuid(getUuid());
        addressBookImpl.setAddressBookId(getAddressBookId());
        addressBookImpl.setGroupId(getGroupId());
        addressBookImpl.setCompanyId(getCompanyId());
        addressBookImpl.setUserId(getUserId());
        addressBookImpl.setUserName(getUserName());
        addressBookImpl.setCreateDate(getCreateDate());
        addressBookImpl.setModifiedDate(getModifiedDate());
        addressBookImpl.setName(getName());
        addressBookImpl.setEmail(getEmail());
        addressBookImpl.setAge(getAge());
        addressBookImpl.setMessage(getMessage());

        addressBookImpl.resetOriginalValues();

        return addressBookImpl;
    }

    @Override
    public int compareTo(AddressBook addressBook) {
        int value = 0;

        if (getAddressBookId() < addressBook.getAddressBookId()) {
            value = -1;
        } else if (getAddressBookId() > addressBook.getAddressBookId()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AddressBook)) {
            return false;
        }

        AddressBook addressBook = (AddressBook) obj;

        long primaryKey = addressBook.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        AddressBookModelImpl addressBookModelImpl = this;

        addressBookModelImpl._originalUuid = addressBookModelImpl._uuid;

        addressBookModelImpl._originalGroupId = addressBookModelImpl._groupId;

        addressBookModelImpl._setOriginalGroupId = false;

        addressBookModelImpl._originalCompanyId = addressBookModelImpl._companyId;

        addressBookModelImpl._setOriginalCompanyId = false;

        addressBookModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<AddressBook> toCacheModel() {
        AddressBookCacheModel addressBookCacheModel = new AddressBookCacheModel();

        addressBookCacheModel.uuid = getUuid();

        String uuid = addressBookCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            addressBookCacheModel.uuid = null;
        }

        addressBookCacheModel.addressBookId = getAddressBookId();

        addressBookCacheModel.groupId = getGroupId();

        addressBookCacheModel.companyId = getCompanyId();

        addressBookCacheModel.userId = getUserId();

        addressBookCacheModel.userName = getUserName();

        String userName = addressBookCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            addressBookCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            addressBookCacheModel.createDate = createDate.getTime();
        } else {
            addressBookCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            addressBookCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            addressBookCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        addressBookCacheModel.name = getName();

        String name = addressBookCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            addressBookCacheModel.name = null;
        }

        addressBookCacheModel.email = getEmail();

        String email = addressBookCacheModel.email;

        if ((email != null) && (email.length() == 0)) {
            addressBookCacheModel.email = null;
        }

        addressBookCacheModel.age = getAge();

        addressBookCacheModel.message = getMessage();

        String message = addressBookCacheModel.message;

        if ((message != null) && (message.length() == 0)) {
            addressBookCacheModel.message = null;
        }

        return addressBookCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(25);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", addressBookId=");
        sb.append(getAddressBookId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", email=");
        sb.append(getEmail());
        sb.append(", age=");
        sb.append(getAge());
        sb.append(", message=");
        sb.append(getMessage());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(40);

        sb.append("<model><model-name>");
        sb.append("com.book.address.model.AddressBook");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>addressBookId</column-name><column-value><![CDATA[");
        sb.append(getAddressBookId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>email</column-name><column-value><![CDATA[");
        sb.append(getEmail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>age</column-name><column-value><![CDATA[");
        sb.append(getAge());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>message</column-name><column-value><![CDATA[");
        sb.append(getMessage());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
